### PR TITLE
自动抓取合并上游服务商的模型列表到现有模型列表

### PR DESCRIPTION
**Pull request by DrayChou**
#### 变更内容：
1. **通过 `/v1/models` 接口抓取上游服务商的模型列表**：
   - 现在 `/v1/models` 接口会抓取上游服务商的 `/v1/models` 列表。

2. **合并模型列表**：
   - 将上游服务商的模型列表合并到现有的 [`models`](command:_github.copilot.openSymbolFromReferences?%5B%22%22%2C%5B%7B%22uri%22%3A%7B%22scheme%22%3A%22file%22%2C%22authority%22%3A%22%22%2C%22path%22%3A%22%2Fe%3A%2Fgit%2Funi-api%2FREADME_CN.md%22%2C%22query%22%3A%22%22%2C%22fragment%22%3A%22%22%7D%2C%22pos%22%3A%7B%22line%22%3A43%2C%22character%22%3A40%7D%7D%5D%2C%2246acf72f-9a35-46a7-82c4-17cf09200fbf%22%5D "Go to definition") 列表中。
   - 如果 [`model`](command:_github.copilot.openSymbolFromReferences?%5B%22%22%2C%5B%7B%22uri%22%3A%7B%22scheme%22%3A%22file%22%2C%22authority%22%3A%22%22%2C%22path%22%3A%22%2Fe%3A%2Fgit%2Funi-api%2FREADME_CN.md%22%2C%22query%22%3A%22%22%2C%22fragment%22%3A%22%22%7D%2C%22pos%22%3A%7B%22line%22%3A45%2C%22character%22%3A4%7D%7D%5D%2C%2246acf72f-9a35-46a7-82c4-17cf09200fbf%22%5D "Go to definition") 字段包含 `"*"`, 则会请求所有可用的模型。

3. **更新 [`README_CN.md`](command:_github.copilot.openRelativePath?%5B%7B%22scheme%22%3A%22file%22%2C%22authority%22%3A%22%22%2C%22path%22%3A%22%2Fe%3A%2Fgit%2Funi-api%2FREADME_CN.md%22%2C%22query%22%3A%22%22%2C%22fragment%22%3A%22%22%7D%2C%2246acf72f-9a35-46a7-82c4-17cf09200fbf%22%5D "e:\git\uni-api\README_CN.md")**：
   - 添加了 [`models_url`](command:_github.copilot.openSymbolFromReferences?%5B%22%22%2C%5B%7B%22uri%22%3A%7B%22scheme%22%3A%22file%22%2C%22authority%22%3A%22%22%2C%22path%22%3A%22%2Fe%3A%2Fgit%2Funi-api%2FREADME_CN.md%22%2C%22query%22%3A%22%22%2C%22fragment%22%3A%22%22%7D%2C%22pos%22%3A%7B%22line%22%3A43%2C%22character%22%3A4%7D%7D%5D%2C%2246acf72f-9a35-46a7-82c4-17cf09200fbf%22%5D "Go to definition") 字段的说明，表示这是后端服务的模型列表地址，选填。
   - 解释了 [`model`](command:_github.copilot.openSymbolFromReferences?%5B%22%22%2C%5B%7B%22uri%22%3A%7B%22scheme%22%3A%22file%22%2C%22authority%22%3A%22%22%2C%22path%22%3A%22%2Fe%3A%2Fgit%2Funi-api%2FREADME_CN.md%22%2C%22query%22%3A%22%22%2C%22fragment%22%3A%22%22%7D%2C%22pos%22%3A%7B%22line%22%3A45%2C%22character%22%3A4%7D%7D%5D%2C%2246acf72f-9a35-46a7-82c4-17cf09200fbf%22%5D "Go to definition") 字段的使用方法，包括如何使用 `"*"` 来表示所有模型，以及如何重命名模型。

#### 修改文件：
- [`request.py`](command:_github.copilot.openRelativePath?%5B%7B%22scheme%22%3A%22file%22%2C%22authority%22%3A%22%22%2C%22path%22%3A%22%2Fe%3A%2Fgit%2Funi-api%2Frequest.py%22%2C%22query%22%3A%22%22%2C%22fragment%22%3A%22%22%7D%2C%2246acf72f-9a35-46a7-82c4-17cf09200fbf%22%5D "e:\git\uni-api\request.py")
- [`utils.py`](command:_github.copilot.openRelativePath?%5B%7B%22scheme%22%3A%22file%22%2C%22authority%22%3A%22%22%2C%22path%22%3A%22%2Fe%3A%2Fgit%2Funi-api%2Futils.py%22%2C%22query%22%3A%22%22%2C%22fragment%22%3A%22%22%7D%2C%2246acf72f-9a35-46a7-82c4-17cf09200fbf%22%5D "e:\git\uni-api\utils.py")
- [`README_CN.md`](command:_github.copilot.openRelativePath?%5B%7B%22scheme%22%3A%22file%22%2C%22authority%22%3A%22%22%2C%22path%22%3A%22%2Fe%3A%2Fgit%2Funi-api%2FREADME_CN.md%22%2C%22query%22%3A%22%22%2C%22fragment%22%3A%22%22%7D%2C%2246acf72f-9a35-46a7-82c4-17cf09200fbf%22%5D "e:\git\uni-api\README_CN.md")

#### 测试：
- 已在本地环境中测试，确保模型列表正确合并。
- 确保 [`provider`](command:_github.copilot.openSymbolFromReferences?%5B%22%22%2C%5B%7B%22uri%22%3A%7B%22scheme%22%3A%22file%22%2C%22authority%22%3A%22%22%2C%22path%22%3A%22%2Fe%3A%2Fgit%2Funi-api%2FREADME_CN.md%22%2C%22query%22%3A%22%22%2C%22fragment%22%3A%22%22%7D%2C%22pos%22%3A%7B%22line%22%3A41%2C%22character%22%3A4%7D%7D%5D%2C%2246acf72f-9a35-46a7-82c4-17cf09200fbf%22%5D "Go to definition") 的 [`base_url`](command:_github.copilot.openSymbolFromReferences?%5B%22%22%2C%5B%7B%22uri%22%3A%7B%22scheme%22%3A%22file%22%2C%22authority%22%3A%22%22%2C%22path%22%3A%22%2Fe%3A%2Fgit%2Funi-api%2FREADME_CN.md%22%2C%22query%22%3A%22%22%2C%22fragment%22%3A%22%22%7D%2C%22pos%22%3A%7B%22line%22%3A42%2C%22character%22%3A4%7D%7D%5D%2C%2246acf72f-9a35-46a7-82c4-17cf09200fbf%22%5D "Go to definition") 根据 `project_id` 和 `cf_account_id` 正确更新。

请审阅并合并这些更改，以合并上游服务商的模型列表到现有模型列表。谢谢！

#### 示例配置：
```yaml
- provider: provider_name # 服务提供商名称, 如 openai、anthropic、gemini、openrouter、deepbricks，随便取名字，必填
    base_url: https://api.your.com/v1/chat/completions # 后端服务的API地址，必填
    models_url: https://api.your.com/v1/models # 后端服务的模型列表地址，选填
    api: sk-YgS6GTi0b4bEabc4C # 提供商的API Key，必填
    model: # 至少填一个模型
      - "*" # 如果填 *，表示可以使用所有模型，会请求 providers 下面设置的所有渠道里面的所有模型，不需要一个个添加可用渠道。
      - gpt-4o # 可以使用的模型名称，必填
      - claude-3-5-sonnet-20240620: claude-3-5-sonnet # 重命名模型，claude-3-5-sonnet-20240620 是服务商的模型名称，claude-3-5-sonnet 是重命名后的名字，可以使用简洁的名字代替原来复杂的名称，选填
      - dall-e-3
```

### CODE REVIEW

**Comment by yym68686** [comment]
你好，还需要修改一下。

**Comment by yym68686** [comment]
没人回应我就关闭了，稍后我自己实现一下。😂

**Comment by DrayChou** [comment]
> 没人回应我就关闭了，稍后我自己实现一下。😂

啊，你要怎么修改？按照你的方式实现就是了。我这个也就是抛砖引玉

**Comment by yym68686** [comment]
好吧，你 pr 到另外一个分支吧，不要合并到主分支，因为还不完善，这样也方便我针对性修改一下，最后合并到主分支。❤️

**Comment by DrayChou** [comment]
> 好吧，你 pr 到另外一个分支吧，不要合并到主分支，因为还不完善，这样也方便我针对性修改一下，最后合并到主分支。❤️

ok

**Comment by yym68686** [comment]
抱歉，我也没用过 pr 到新分支，需要我手动操作一下，这就给你合并。

**Pull request merged**
